### DISCUSSION TITLE
CRON UTC time generator

### DISCUSSION THREAD

**Discussion by Yohn** [CorentinTh/it-tools#261] [Ideas]
I've been playing around more with the [schedule setting](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule) in GitHub workflows and there isn't an easy way to figure out what time the UTC time is compared to my timezone I'm in.

If we could have a way to set the timezone, and then all the * within the cron that would be awesome.  

Below is a code snippet that I've been using to help me figure out how to set the schedule. 

````yaml
on:
  # Schedule daily updates
  # each [] below is the option we can set according to the info under it.
  # [min (0-59)] [hour (0-23)] [day of month (1-31)] [month (1-12)] [day of week (0-6)]
  # 0 11 means its running at 6AM EST 
  schedule: [{cron: "10 5 * * *"}]
````
