### DISCUSSION TITLE
Password strength analyser

### DISCUSSION THREAD

**Discussion by grannymaster** [CorentinTh/it-tools#531] [Q&A]
Hello, 

Am I missing something or did I do something wrong, when comparing the https://it-tools.tech to my own IT-Tools hosted in docker, it seems to be missing some tools. For example, I don't seem to have access to the "Password strength analyzer".
https://i.imgur.com/DLjWtfd.png

Local instance version:

```
IT-Tools[ v2023.5.14-77f2efc](https://github.com/CorentinTh/it-tools/tree/v2023.5.14-77f2efc)
© 2023 Corentin Thomasset
```

Docker compose configuration:

```
version: '3.9'
services:
    corentinth:
        image: 'ghcr.io/corentinth/it-tools:latest'
        ports:
            - '8080:80'
        restart: unless-stopped
        container_name: it-tools

```
