### ISSUE TITLE
NGINX Proxy Manager configuration

### ISSUE THREAD

**Issue by altendorfme** [CorentinTh/it-tools#1285]
### Describe the bug

I created a basic it-tools stack:

```
services:
  it-tools:
    container_name: it-tools
    image: corentinth/it-tools
    ports:
      - 8080:80
    restart: unless-stopped
    networks:
      - reverse-proxy
networks:
  reverse-proxy:
    external: true
```

I have several other projects like ladder, linkding working in the same flow, but particularly it-tools seems to be blocking something so that Nginx Proxy does not see port 8080

I can access port 8080 locally and see IT-Tools

### What happened?

Nginx Proxy does not see port 8080

### System information

Docker

### Where did you encounter the bug?

A self hosted

**Comment by ledakis** [comment]
Hey, this setup has worked for me. In nginx proxy manager I set it to connect to `it-tools:80` not `8080`

```
version: '3.3'
name: it-tools
services:
    it-tools:
        container_name: it-tools
        restart: unless-stopped
        # ports:
        #     - 8080:80
        image: ghcr.io/corentinth/it-tools:latest


networks:
  default:
    external:
      name: proxy-net
```
