### ISSUE TITLE
Incorrect yaml anchors encoding

### ISSUE THREAD

**Issue by d-enk** [CorentinTh/it-tools#1333]
### Describe the bug

`<<: *` not encoded

```yaml
default: &default
  name: ''
  age: 0

person:
  *default

persons:
- <<: *default
  age: 1
- <<: *default
  name: John
- { age: 3, <<: *default }
```

### What happened?

actual
```json
{
   "default": {
      "name": "",
      "age": 0
   },
   "person": {
      "name": "",
      "age": 0
   },
   "persons": [
      {
         "<<": {
            "name": "",
            "age": 0
         },
         "age": 1
      },
      {
         "<<": {
            "name": "",
            "age": 0
         },
         "name": "John"
      },
      {
         "age": 3,
         "<<": {
            "name": "",
            "age": 0
         }
      }
   ]
}
```

expected
```json
{
  "default": {
    "name": "",
    "age": 0
  },
  "person": {
    "name": "",
    "age": 0
  },
  "persons": [
    {
      "name": "",
      "age": 1
    },
    {
      "name": "John",
      "age": 0
    },
    {
      "age": 3,
      "name": ""
    }
  ]
}
```

### System information

  System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
  Browsers:
    Chrome: 129.0.6668.89

### Where did you encounter the bug?

Public app (it-tools.tech)
