### ISSUE TITLE
Add to favorites from inside a tool

### ISSUE THREAD

**Issue by ajpanton** [CorentinTh/it-tools#1384]
### Describe the bug

When viewing the grid of tools, you can click the heart to add a tool to your favorites. This works fine.

When opening a tool, there's the heart again in the upper-right corner. Here the heart does nothing.

### What happened?

Nothing happens. I expected it to be added to my favorites. Similarly, if a tool is already in the favorites, clicking this heart doesn't remove it.

### System information

Docker container, very vanilla settings, just a port mapping.

### Where did you encounter the bug?

A self hosted

**Comment by gitmotion** [comment]
this should be fixed here: https://github.com/CorentinTh/it-tools/pull/1368

and it's working in it-tools.tech - by any chance have you pulled/redeployed with the latest version? you may need to clear cache and hard reload (ctrl + shift + r) after redeploying

**Comment by gitmotion** [comment]
@ajpanton ah interesting, in that case you might want to try the nightly github package/image that should have all the newest changes: [ghcr.io/corentinth/it-tools:nightly](https://github.com/CorentinTh/it-tools/pkgs/container/it-tools)

``` 
services:
    it-tools:
        image: 'ghcr.io/corentinth/it-tools:nightly'
        container_name: it-tools
        restart: unless-stopped
        ports:
            - '8080:80'
```
