### ISSUE TITLE
[BUG] docker run converter not working correctly on selfhosted version

### ISSUE THREAD

**Issue by devcircus** [CorentinTh/it-tools#301]
**Describe the bug**
Using the docker run command from the It-tools github homepage gives the following docker-compose file:
```yaml
version: '3.3'
services:
    run:
        ports:
            - '8080:80'
        container_name: it-tools
        image: run

```

**To Reproduce**
1. Go to the [it-tools github](https://github.com/CorentinTh/it-tools) homepage 
2. Copy the docker run command: `docker run -d -p 8080:80 --name it-tools -it corentinth/it-tools`
3. Paste in the docker run converter field
4. See the incorrect docker-compose result

**Expected behavior**
Expected to see the image name translated correctly from the docker run command

**Configuration (please complete the following information):**
 - Host Device: dell t3600
 - Host OS: Ubuntu 22.10 
 - Client Browser: Brave 1.49.120
 - Version: latest
