### ISSUE TITLE
[NEW TOOL] Properties to YAML converter

### ISSUE THREAD

**Issue by Yann39** [CorentinTh/it-tools#411]
**What tool do you want?**
A properties to yaml converter.
[`properties`](https://en.wikipedia.org/wiki/.properties) are mainly used in Java for configuration files.

**Describe the solution you'd like**
The tool should allow to provide a content in `properties` format, and obtain the equivalent in `yaml` format.
Possibly the reverse could also be interesting.

i.e.

```properties
# Server
server.port=                                                    8080
server.http2.enabled=                                           true
server.ssl.enabled=                                             true
server.ssl.key-alias=                                           localhost

# Database
spring.datasource.url=                                          jdbc:mysql://localhost:3306/db
spring.datasource.username=                                     root
spring.datasource.password=                                     1234
```

```yaml
# Server
server:
    http2:
        enabled: true
    port: 8080
    ssl:
        enabled: true
        key-alias: localhost
# Database
spring:
    datasource:
        password: 1234
        url: jdbc:mysql://localhost:3306/db
        username: root
```

**Is their example of this tool in the wild?**
There are several examples on the net, and there is also an [Intellij plugin](https://plugins.jetbrains.com/plugin/8000-properties-to-yaml-converter).

**Additional context**
This could be useful to avoid having to use online tools or plugins, as such configuration files often contain sensitive information.
