### ISSUE TITLE
[NEW TOOL] docker-compose-to-docker-run-converter

### ISSUE THREAD

**Issue by f0sh** [CorentinTh/it-tools#546]
**What tool do you want?**
Currently there is [docker-run-to-docker-compose-converter](https://github.com/CorentinTh/it-tools/tree/main/src/tools/docker-run-to-docker-compose-converter). Would be awesome to have the other way round as well: Quickly convert a Docker Run command into a Compose file.

**Is their example of this tool in the wild?**
https://8gwifi.org/dc2.jsp
Unfortunately it is only a serverside tool.

**Comment by tobiashochguertel** [comment]
I would appreciate it if we could configure the converter so that we can generate quickly standard docker compose files with some additional settings like traefik labels.

```yaml
version: '3.9'

networks:
  proxy:
    external: true
  intranet:
    external: true

services:
  it-tools:
    image: 'corentinth/it-tools:latest'
    # ports:
    # - '8080:80'
    restart: unless-stopped
    container_name: it-tools
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # https://it-tools.vps4.hochguertel.work
      - "traefik.http.routers.it-tools.entrypoints=http"
      - "traefik.http.routers.it-tools.rule=Host(`it-tools.vps4.hochguertel.work`)"
      - "traefik.http.routers.it-tools.service=it-tools"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
      - "traefik.http.middlewares.it-tools-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.it-tools.middlewares=it-tools-https-redirect"
      - "traefik.http.routers.it-tools-secure.entrypoints=https"
      - "traefik.http.routers.it-tools-secure.rule=Host(`it-tools.vps4.hochguertel.work`)"
      - "traefik.http.routers.it-tools-secure.service=it-tools"
      - "traefik.http.routers.it-tools-secure.tls=true"
      - "traefik.http.routers.it-tools-secure.tls.certresolver=http"
    networks:
      - proxy
      - intranet
```
