### ISSUE TITLE
Docker to Docker compose Tool: Improve by adding common settings to a compose file.

### ISSUE THREAD

**Issue by tobiashochguertel** [CorentinTh/it-tools#639]
**Describe the solution you'd like**
I would appreciate it if we could configure the converter so that we can generate quickly standard docker compose files with some additional settings like traefik labels.

It would be great to have a way to add common additions to the Compose file like `labels`, `networks` and so on. I think on something like that we can choice from a dropdown menu the settings which we want to apply to the compose file.

**Additional context**

here is a example how my compose files often look, I work much with traefik and let's encrypt so I have there two networks which I add and labels to configure traefik.

```yaml
version: '3.9'

networks:
  proxy:
    external: true
  intranet:
    external: true

services:
  it-tools:
    image: 'corentinth/it-tools:latest'
    # ports:
    # - '8080:80'
    restart: unless-stopped
    container_name: it-tools
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # https://it-tools.vps4.hochguertel.work
      - "traefik.http.routers.it-tools.entrypoints=http"
      - "traefik.http.routers.it-tools.rule=Host(`it-tools.vps4.hochguertel.work`)"
      - "traefik.http.routers.it-tools.service=it-tools"
      - "traefik.http.services.it-tools.loadbalancer.server.port=80"
      - "traefik.http.middlewares.it-tools-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.it-tools.middlewares=it-tools-https-redirect"
      - "traefik.http.routers.it-tools-secure.entrypoints=https"
      - "traefik.http.routers.it-tools-secure.rule=Host(`it-tools.vps4.hochguertel.work`)"
      - "traefik.http.routers.it-tools-secure.service=it-tools"
      - "traefik.http.routers.it-tools-secure.tls=true"
      - "traefik.http.routers.it-tools-secure.tls.certresolver=http"
    networks:
      - proxy
      - intranet
```
